version: '3'
services:

  postgres:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=textwatermark
      - POSTGRES_PASSWORD=textwatermark
      - POSTGRES_USER=textwatermark
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432


  fastapi:
    depends_on:
      - postgres
    build:
      context: ./docker
      dockerfile: ./docker/DockerFile
    restart: on-failure:10
    volumes:
      - ./src/textwatermark_service:/code/textwatermark_service
      - ./src/static:/code/static
    ports:
      - 8000:8000
    environment:
      WAIT_HOSTS: postgres:5432
      TEXTWATERMARKSERV_AUTHORIZE_KEY: d0f4ac8c14eae3a992aa574a55099e4f
      TEXTWATERMARKSERV_POSTGRES_HOST: postgres
      TEXTWATERMARKSERV_POSTGRES_PORT: 5432
      TEXTWATERMARKSERV_POSTGRES_DB: textwatermark
      TEXTWATERMARKSERV_POSTGRES_PASSWORD: textwatermark
      TEXTWATERMARKSERV_POSTGRES_USER: textwatermark

 